import type { IBlog, ICourse, IVideoPreview } from "@/types.d";

export const videoPreviewDummyData: IVideoPreview[] = [
  {
    id: "video-1",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 1",
    description: "Video description 1",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-2",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 2",
    description: "Video description 2",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-3",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 3",
    description: "Video description 3",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-4",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 4",
    description: "Video description 4",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-5",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 5",
    description: "Video description 5",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-6",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 6",
    description: "Video description 6",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-7",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 7",
    description: "Video description 7",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-8",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 8",
    description: "Video description 8",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-9",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 9",
    description: "Video description 9",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-10",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 10",
    description: "Video description 10",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-11",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 11",
    description: "Video description 11",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-12",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 12",
    description: "Video description 12",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-13",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 13",
    description: "Video description 13",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-14",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 14",
    description: "Video description 14",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-15",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 15",
    description: "Video description 15",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-16",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 16",
    description: "Video description 16",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-17",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 17",
    description: "Video description 17",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-18",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 18",
    description: "Video description 18",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-19",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 19",
    description: "Video description 19",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-20",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 20",
    description: "Video description 20",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-21",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 21",
    description: "Video description 21",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-22",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 22",
    description: "Video description 22",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-23",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 23",
    description: "Video description 23",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-24",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 24",
    description: "Video description 24",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-25",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 25",
    description: "Video description 25",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-26",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 26",
    description: "Video description 26",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
  {
    id: "video-27",
    thumbnailURL: "https://picsum.photos/300/200",
    title: "Video Title 27",
    description: "Video description 27",
    publishedAt: "2024-12-20T00:00:00Z",
    views: "1000",
  },
] as const;

export const blogDummyData: IBlog[] = [
  {
    title: "Blog Title 1",
    mediumURL: "https://medium.com/blog-1",
    description: "Blog description 1",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 2",
    mediumURL: "https://medium.com/blog-2",
    description: "Blog description 2",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 3",
    mediumURL: "https://medium.com/blog-3",
    description: "Blog description 3",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 4",
    mediumURL: "https://medium.com/blog-4",
    description: "Blog description 4",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 5",
    mediumURL: "https://medium.com/blog-5",
    description: "Blog description 5",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 6",
    mediumURL: "https://medium.com/blog-6",
    description: "Blog description 6",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 7",
    mediumURL: "https://medium.com/blog-7",
    description: "Blog description 7",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 8",
    mediumURL: "https://medium.com/blog-8",
    description: "Blog description 8",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 9",
    mediumURL: "https://medium.com/blog-9",
    description: "Blog description 9",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 10",
    mediumURL: "https://medium.com/blog-10",
    description: "Blog description 10",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 11",
    mediumURL: "https://medium.com/blog-11",
    description: "Blog description 11",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 12",
    mediumURL: "https://medium.com/blog-12",
    description: "Blog description 12",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 13",
    mediumURL: "https://medium.com/blog-13",
    description: "Blog description 13",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 14",
    mediumURL: "https://medium.com/blog-14",
    description: "Blog description 14",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 15",
    mediumURL: "https://medium.com/blog-15",
    description: "Blog description 15",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 16",
    mediumURL: "https://medium.com/blog-16",
    description: "Blog description 16",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 17",
    mediumURL: "https://medium.com/blog-17",
    description: "Blog description 17",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 18",
    mediumURL: "https://medium.com/blog-18",
    description: "Blog description 18",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 19",
    mediumURL: "https://medium.com/blog-19",
    description: "Blog description 19",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 20",
    mediumURL: "https://medium.com/blog-20",
    description: "Blog description 20",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 21",
    mediumURL: "https://medium.com/blog-21",
    description: "Blog description 21",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 22",
    mediumURL: "https://medium.com/blog-22",
    description: "Blog description 22",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 23",
    mediumURL: "https://medium.com/blog-23",
    description: "Blog description 23",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 24",
    mediumURL: "https://medium.com/blog-24",
    description: "Blog description 24",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 25",
    mediumURL: "https://medium.com/blog-25",
    description: "Blog description 25",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 26",
    mediumURL: "https://medium.com/blog-26",
    description: "Blog description 26",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Blog Title 27",
    mediumURL: "https://medium.com/blog-27",
    description: "Blog description 27",
    thumbnailURL: "https://picsum.photos/300/200",
  },
] as const;

export const courseDummyData: ICourse[] = [
  {
    title: "Course Title 1",
    headline: "Course Headline 1",
    contentInfo: "1 hours of content",
    numLectures: "1 lectures",
    instructionalLevel: "Beginner",
    numReviews: "0 reviews",
    udemyURL: "https://udemy.com/course-1",
    rating: "1.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 2",
    headline: "Course Headline 2",
    contentInfo: "2 hours of content",
    numLectures: "2 lectures",
    instructionalLevel: "Advanced",
    numReviews: "37 reviews",
    udemyURL: "https://udemy.com/course-2",
    rating: "2.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 3",
    headline: "Course Headline 3",
    contentInfo: "3 hours of content",
    numLectures: "3 lectures",
    instructionalLevel: "Beginner",
    numReviews: "74 reviews",
    udemyURL: "https://udemy.com/course-3",
    rating: "3.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 4",
    headline: "Course Headline 4",
    contentInfo: "4 hours of content",
    numLectures: "4 lectures",
    instructionalLevel: "Advanced",
    numReviews: "111 reviews",
    udemyURL: "https://udemy.com/course-4",
    rating: "4.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 5",
    headline: "Course Headline 5",
    contentInfo: "5 hours of content",
    numLectures: "5 lectures",
    instructionalLevel: "Beginner",
    numReviews: "148 reviews",
    udemyURL: "https://udemy.com/course-5",
    rating: "5.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 6",
    headline: "Course Headline 6",
    contentInfo: "6 hours of content",
    numLectures: "6 lectures",
    instructionalLevel: "Advanced",
    numReviews: "185 reviews",
    udemyURL: "https://udemy.com/course-6",
    rating: "1.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 7",
    headline: "Course Headline 7",
    contentInfo: "7 hours of content",
    numLectures: "7 lectures",
    instructionalLevel: "Beginner",
    numReviews: "222 reviews",
    udemyURL: "https://udemy.com/course-7",
    rating: "2.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 8",
    headline: "Course Headline 8",
    contentInfo: "8 hours of content",
    numLectures: "8 lectures",
    instructionalLevel: "Advanced",
    numReviews: "259 reviews",
    udemyURL: "https://udemy.com/course-8",
    rating: "3.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 9",
    headline: "Course Headline 9",
    contentInfo: "9 hours of content",
    numLectures: "9 lectures",
    instructionalLevel: "Beginner",
    numReviews: "296 reviews",
    udemyURL: "https://udemy.com/course-9",
    rating: "4.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 10",
    headline: "Course Headline 10",
    contentInfo: "10 hours of content",
    numLectures: "10 lectures",
    instructionalLevel: "Advanced",
    numReviews: "333 reviews",
    udemyURL: "https://udemy.com/course-10",
    rating: "5.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 11",
    headline: "Course Headline 11",
    contentInfo: "11 hours of content",
    numLectures: "11 lectures",
    instructionalLevel: "Beginner",
    numReviews: "370 reviews",
    udemyURL: "https://udemy.com/course-11",
    rating: "1.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 12",
    headline: "Course Headline 12",
    contentInfo: "12 hours of content",
    numLectures: "12 lectures",
    instructionalLevel: "Advanced",
    numReviews: "407 reviews",
    udemyURL: "https://udemy.com/course-12",
    rating: "2.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 13",
    headline: "Course Headline 13",
    contentInfo: "13 hours of content",
    numLectures: "13 lectures",
    instructionalLevel: "Beginner",
    numReviews: "444 reviews",
    udemyURL: "https://udemy.com/course-13",
    rating: "3.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 14",
    headline: "Course Headline 14",
    contentInfo: "14 hours of content",
    numLectures: "14 lectures",
    instructionalLevel: "Advanced",
    numReviews: "481 reviews",
    udemyURL: "https://udemy.com/course-14",
    rating: "4.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 15",
    headline: "Course Headline 15",
    contentInfo: "15 hours of content",
    numLectures: "15 lectures",
    instructionalLevel: "Beginner",
    numReviews: "518 reviews",
    udemyURL: "https://udemy.com/course-15",
    rating: "5.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 16",
    headline: "Course Headline 16",
    contentInfo: "16 hours of content",
    numLectures: "16 lectures",
    instructionalLevel: "Advanced",
    numReviews: "555 reviews",
    udemyURL: "https://udemy.com/course-16",
    rating: "1.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 17",
    headline: "Course Headline 17",
    contentInfo: "17 hours of content",
    numLectures: "17 lectures",
    instructionalLevel: "Beginner",
    numReviews: "592 reviews",
    udemyURL: "https://udemy.com/course-17",
    rating: "2.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 18",
    headline: "Course Headline 18",
    contentInfo: "18 hours of content",
    numLectures: "18 lectures",
    instructionalLevel: "Advanced",
    numReviews: "629 reviews",
    udemyURL: "https://udemy.com/course-18",
    rating: "3.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 19",
    headline: "Course Headline 19",
    contentInfo: "19 hours of content",
    numLectures: "19 lectures",
    instructionalLevel: "Beginner",
    numReviews: "666 reviews",
    udemyURL: "https://udemy.com/course-19",
    rating: "4.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 20",
    headline: "Course Headline 20",
    contentInfo: "20 hours of content",
    numLectures: "20 lectures",
    instructionalLevel: "Advanced",
    numReviews: "703 reviews",
    udemyURL: "https://udemy.com/course-20",
    rating: "5.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 21",
    headline: "Course Headline 21",
    contentInfo: "21 hours of content",
    numLectures: "21 lectures",
    instructionalLevel: "Beginner",
    numReviews: "740 reviews",
    udemyURL: "https://udemy.com/course-21",
    rating: "1.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 22",
    headline: "Course Headline 22",
    contentInfo: "22 hours of content",
    numLectures: "22 lectures",
    instructionalLevel: "Advanced",
    numReviews: "777 reviews",
    udemyURL: "https://udemy.com/course-22",
    rating: "2.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 23",
    headline: "Course Headline 23",
    contentInfo: "23 hours of content",
    numLectures: "23 lectures",
    instructionalLevel: "Beginner",
    numReviews: "814 reviews",
    udemyURL: "https://udemy.com/course-23",
    rating: "3.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 24",
    headline: "Course Headline 24",
    contentInfo: "24 hours of content",
    numLectures: "24 lectures",
    instructionalLevel: "Advanced",
    numReviews: "851 reviews",
    udemyURL: "https://udemy.com/course-24",
    rating: "4.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 25",
    headline: "Course Headline 25",
    contentInfo: "25 hours of content",
    numLectures: "25 lectures",
    instructionalLevel: "Beginner",
    numReviews: "888 reviews",
    udemyURL: "https://udemy.com/course-25",
    rating: "5.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 26",
    headline: "Course Headline 26",
    contentInfo: "26 hours of content",
    numLectures: "26 lectures",
    instructionalLevel: "Advanced",
    numReviews: "925 reviews",
    udemyURL: "https://udemy.com/course-26",
    rating: "1.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
  {
    title: "Course Title 27",
    headline: "Course Headline 27",
    contentInfo: "27 hours of content",
    numLectures: "27 lectures",
    instructionalLevel: "Beginner",
    numReviews: "962 reviews",
    udemyURL: "https://udemy.com/course-27",
    rating: "2.0",
    thumbnailURL: "https://picsum.photos/300/200",
  },
] as const;
